### ISSUE TITLE
let the github page load the README.md automatically

### ISSUE THREAD

**Issue by haoliangyu** [RoboDonut/awesome-spatial#79]
let the .io page automatically load the `README.md` at master branch and compile it to html on-the-fly. So that we don't need to worry much about the update of website. To achieve it, the github page will be turned into an Angular app and use [angular-marked](https://github.com/Hypercubed/angular-marked).

This guy is work on it: @haoliangyu

**Task List**

- [x] rewrite the github page into an Angular app
- [x] load and compile `README.md` on-the-fly
- [x] add GitHub star button

**Comment by RoboDonut** [comment]
How does the current `README.md` need to be altered to support? 

With this upgrade to the .io page i'd really like to see a the addition of the github buttons, specifically the stars button so folks can book mark straight away.

**Comment by haoliangyu** [comment]
The github page should have exactly the same content of the `README.md`, so I think there is no need to change the README.md. As for the github start button, I have already found a solution: [github-buttons](https://github.com/ntkme/github-buttons).

I will probably start working on this next week.

**Comment by RoboDonut** [comment]
does this allow you to star directly or just hyperlink to the page? If the star count is accurate I'm cool with the hyperlink.

**Comment by haoliangyu** [comment]
According to the [example of github-buttons](https://buttons.github.io/), the button itself is just a hyperlink to the project repo and the number of stars is fetched from GitHub API (real-time!!). It should meet your requirement.

**Comment by haoliangyu** [comment]
@RoboDonut I have made the change at [https://haoliangyu.github.io/awesome-spatial/](https://haoliangyu.github.io/awesome-spatial/). How do you think?
